### ISSUE TITLE
Add Applet to Public Library 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#1]
As an owner or manager of an applet, I want to share my applet with the library so that others can use it for their needs. 

Requirements 
* For owners and managers, add a globe icon that will be the way an applet is shared with the library 
* Display pop with text and on/ off switch
* Applets shared with the library cannot have the same name 
** If the applet has the same name then show a message with the ability to change the name which changes the applets name for the owner and the library 
** If the replacement name is taken as well, show the error message 
* Require the user to select the category and subcategory of the applet 
* Allow the user to enter keywords if necessary 
* Once the user hits publish, the applet should be live on library.mindlogger.com 
* Allow the user to change the category, sub-category, and keywords
* Show a hyperlink text "Copy link to share with others"
** When the user clicks this show a "Copied!" text and copy the URL to the user's clipboard to paste outside of MindLogger

![Share applet with public .png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/51651888-d04b-4b44-bab4-1084c0ef694f)

**Comment by WorldImpex** [comment]
backend complete

**Comment by Sshetty2** [comment]
After a user publishes an applet, 
it should be possible for him to update that applet content in the library by clicking the globe icon again, right?

for example, if he wants to update the category / subCategory / keywords for that applet in the library,
or he may want to unpublish that applet by switching it off ...

Let me know.

**Comment by WorldImpex** [comment]
@Sshetty2 Yes the user should be able to unpublish, change cat/ subcat, etc

**Comment by Sshetty2** [comment]
https://github.com/ChildMindInstitute/mindlogger-admin/pull/878

**Comment by sergeysemenuta** [comment]
Testing is blocked by [948](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/948)

**Comment by natalia-muzyka** [comment]
The keywords aren't updated after adding a new keyword to the shared applet [#1036](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1036)

**Comment by natalia-muzyka** [comment]
"Require the user to select the category and subcategory of the applet" isn't implemented according to the ticket:
[#1020 Hide category, sub-category when sharing an applet with library](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1020)

Fixed:
The keywords aren't updated after adding a new keyword to the shared applet #1036

Waiting for the fix:
[#1014 There is a wrong path for a copied link to share an applet with others](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1014)

**Comment by natalia-muzyka** [comment]
All the issues are fixed.
Works as expected except the:

> Allow the user to change the category, sub-category, and keywords 

According to this ticket https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/40

Checked on:
Win 10 // Chrome 91.0.4472.124
