### ISSUE TITLE
The checkout process is continued after clicking the "Add to applet builder" button in the empty cart by logged-in user

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-applet-library#103]
**Steps to reproduce**
1. Open a site https://library-staging.mindlogger.org/
2. Log in: geria.test@gmail.com // 123456
3. Click the checkout(basket) button(the basket should be empty)
4. Click the "Add to applet builder" button
5. Pay attention to the screen

**Actual result**
The checkout process is continued after clicking the "Add to applet builder" button in the empty cart, the user is able to proceed to the applet builder, 

**Expected result**
There should be a warning (pop-up) that the user has not added anything to the basket yet.
@WorldImpex the text for pop-up should be confirmed.
Suggestion: "You have not added anything to your basket yet"

**Video**: https://www.screencast.com/t/TWujnxL4BS7

**Environment**
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124

**Comment by WorldImpex** [comment]
@natalia-muzyka confirmed

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/dp3FPwus3N

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.124
macOS 10.15 // Safari
