### ISSUE TITLE
The "Adding content for the applet you are currently creating" bar is disappeared after clicking the ML logo / Applet library

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-applet-library#116]
**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Log in: johndoeregress@protonmail.com	// 12345678
3. Click on the "Edit" button on any applet
4. Click on the "Import from library" button in the applet builder
5. Click on the ML logo
6. Pay attention to the screen

**Actual result**
The "Adding content for the applet you are currently creating" bar is disappeared after clicking the ML logo / Applet library

**Expected result**
The "Adding content for the applet you are currently creating" bar is still displayed after clicking the ML logo / Applet library

**Video:** https://www.screencast.com/t/QtX4fXj3l7

**Environment:**
https://admin-staging.mindlogger.org/
https://library-staging.mindlogger.org/
Win 10 // Chrome 93.0.4577.82 
macOS 11.0 // Safari 14.0.1
johndoeregress@protonmail.com	// 12345678

**Comment by natalia-muzyka** [comment]
After fixing this issue the [old issue](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/109)(search results aren't removed after clicking the ML logo) started to reproduce again.
Video: https://www.screencast.com/t/iSkwVWuAV8U

@Sshetty2 @devbtech could you please confirm how this should be resolved without breaking the #109?

**Comment by astef021** [comment]
could you please recheck this issue?

https://images.zenhubusercontent.com/343540842/197cd0e8-9e00-4606-9c59-239f3400d92d/video.mov

**Comment by natalia-muzyka** [comment]
@astef021 issue is still reproducible with these steps:

1. Open a site https://admin-staging.mindlogger.org/
2. Log in: johndoeregress@protonmail.com // 12345678
3. Click on the "Edit" button on any applet
4. Click on the "Import from library" button in the applet builder
5. Proceed to the cart
6. Click on the ML logo
7. Reload the page
8. Pay attention to the screen

Video: https://www.screencast.com/t/qm4gjUMs

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 95.0.4638.69

**Comment by natalia-muzyka** [comment]
Verified as fixed. tested with steps in the ticket and in the comment above.
Video: https://www.screencast.com/t/N7NSev4frnIC

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 96.0.4664.45
