### ISSUE TITLE
Add Applet Logo to the top right corner of PDF Export

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#135]
If the editor adds an applet image, add that image to the top right corner of the PDF export

![Peds-Screening-Report-Changes-wavanauken-gmail-com-Gmail.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/9302d880-8910-476f-8966-53e62f8c8fd7)

Logo assets: https://childmindinstitute759-my.sharepoint.com/:f:/g/personal/abby_brewster_childmind_org/Et8MGdXIrNdOuT9oPQHNacgBsFxGqCSCtzKSUEpO0CGosQ?e=2l5oyF

**Comment by natalia-muzyka** [comment]
**Issues:**
The Applet image isn't displayed as a logo in the PDF mobile report [#2067](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2067)
The Applet image uploaded from PC isn't displayed as a logo in the admin PDF report [#1312](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1312)
