### ISSUE TITLE
Add file name and download button to image uploaders

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#146]
Where an editor has added an image, the editor needs a way to see what the file name was and a way to re-download the image 
This should be implemented for every image upload widget, (splash screen, watermark, header image, canvas image, etc) 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/cc7809e1-512b-4a1f-9484-3fe339c1492b)

**Comment by natalia-muzyka** [comment]
@binaryExDev @devbtech I don't see any changes. Was there a deployment issue?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/bf8b9dab-2d50-4070-bbcc-0df411a648c8)

**Comment by WorldImpex** [comment]
No changes still 

![Screen Shot 2022-01-12 at 7.12.15 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/11d432d8-92d2-4c7f-9ebd-b63a54da8459)

**Comment by WorldImpex** [comment]
@binaryExDev Yes that is fine

**Comment by natalia-muzyka** [comment]
@devbtech @WorldImpex 
1. Uploaded from PC image name doesn't match the original name (if this was the purpose). There is the autogenerated name.
2. There's no way to download the uploaded image

Video: https://www.screencast.com/t/9cxsxufWndZ

**Comment by natalia-muzyka** [comment]
The feature is not implemented at all for:
- About image
- Splash image
- Activity image
- Header image (Radio, checkbox, slider, text, time range, date, photo, video, audio, audio image, audio stimulus, drawing, Stacked radio, Stacked checkbox, Stacked slider)
- Audio record image
- Geolocation image
- Draw image, Draw Background image
- Stacked radio (response options, item list)
- Stacked checkbox (response options, item list)

New issues:
Some of the uploaded images aren't downloaded after clicking on filename#691
The name of the downloaded file doesn't match the name displayed on the admin panel(applet builder) #690

**Comment by natalia-muzyka** [comment]
@binaryExDev  Still not implemented for:
About page image: https://www.screencast.com/t/wRr6MFQ8ZMB
Splash image: https://www.screencast.com/t/35R4Sv0H

**Comment by natalia-muzyka** [comment]
Fixed for About page image and Splash image: 
https://www.screencast.com/t/AvH45ywHOc
https://www.screencast.com/t/rnPkzJpzsSF

**Comment by WorldImpex** [comment]
@natalia-muzyka Is this one we can close?

**Comment by natalia-muzyka** [comment]
The last I was waiting for (it's on dev complete) https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/691

**Comment by WorldImpex** [comment]
Thanks @natalia-muzyka! @binaryExDev stated that it is an issue with other websites that happens randomly so I think we can backlog that bug and close this ticket

**Comment by natalia-muzyka** [comment]
ok, thank you for clarification @WorldImpex , other than this issue the implemented feature met the requirements.

Verified on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 98.0.4758.82
macOS 10.15 // Chrome 98.0.4758.82 // Safari 13.1.2
