### ISSUE TITLE
The applet is not removed from the cart after clicking "ok" on "Delete applet" pop up

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-applet-library#151]
**Steps to reproduce**
1. Open a site: https://library-staging.mindlogger.org/
2. Add at least two applets to the cart
3. Open the cart page
4. Click the "Delete" button on any applet
5. Click the "Ok" button in the "Delete applet" pop up
6. Pay attention to the screen
7. Refresh the page
8. Pay attention to the screen

**Actual result**
The applet is not removed from the cart after clicking "ok" on the "Delete applet" pop up. The applet is deselected and removed only after refreshing the page.

**Expected result**
The applet is removed from the cart after clicking "ok" on the "Delete applet" pop up.

**Video:** https://www.screencast.com/t/GlTtvZ7I

**Environment:**
https://library-staging.mindlogger.org/
Win 10 // Chrome 96.0.4664.110

**Comment by natalia-muzyka** [comment]
@astef021 
Applet is removed after clicking "ok" as well as after clicking "cancel" now.
If user clicks "cancel" then applet shouldn't be deselected and removed. It should stay in the cart.
Video: https://www.screencast.com/t/AZigxKtll9

https://library-staging.mindlogger.org/
Win 10 // Chrome 96.0.4664.110

**Comment by WorldImpex** [comment]
works as expected
