### ISSUE TITLE
Export All Reports from a Daisy Chain

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#157]
As a user, I want to take activities that are daisy-chained together and at the end of the chain I want to export all reports so that I can focus on inputting answers and worry about all PDF reports at the end 

Requirements 
- At the applet level, add a checkbox "Combine reports on last activity" 
- At the last activity in the chain, add a Share all Reports button to the cumulative summary screen 
- Functionally the share button works the same as the original but contains all reports within the chain of activities 
- User should still have access to the Share report button and an additional button is added called Share All Reports

**Comment by WorldImpex** [comment]
Steps to reproduce 
1. Sign into mobile 
2. Execute activities in a chain 
3. On last screen of activity 3 with cumulative score, see results

Expected: There are two buttons Share report/ Share All Reports. The user can view either PDF. The last activity must have "allow user to see results" and "share all reports" selected to view these buttons. 
Actual: Only Share Report button is present 

owner: loui_ml@protonmail.com // 12345678
applet: daisy chain loop
password: Qwe123!!!

**Comment by WorldImpex** [comment]
Share all Reports button is present but Share Report only shows the footer in the report

**Comment by natalia-muzyka** [comment]
The issue above is fixed.

**Comment by natalia-muzyka** [comment]
1. Will this be a common case when admin sets up a splash screen for every activity (not only for the first one in the chain)? If yes, then we need to fix the old issue. If there is more than one splash screen then all the next splash screens will be displayed incorrectly on mobile app and admin panel:
Samsung S7 Edge / ML v0.18.54: https://www.screencast.com/t/7BMRpq7U9
Win 10 Chrome: https://www.screencast.com/t/izqRcQxd
Report: https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-web/219

2. This feature is for mobile and webapp only, right? The admin panel report still includes all the latest data for all completed activities (no matter are they chained or not). Suggest adding some tooltip with additional info to "Combine reports on last activity" (so editor could understand that this effort is only for user side and there should be allowed "see results" checkbox in the last activity as well)

**Comment by natalia-muzyka** [comment]
@WorldImpex could you take a look on my comment above, please?

**Comment by WorldImpex** [comment]
1. Yes I added that ticket to the sprint backlog
2. I agree - I will put up a ticket for it 
3. I think we can leave activity title for now

**Comment by natalia-muzyka** [comment]
@mtg137

**Comment by natalia-muzyka** [comment]
1 - there are still a few issues for splash screen, which aren't a blocker, so ticket #219 is backlogged
2 - fixed

Verified and closed.
Environment:
ML v0.18.61 staging
Samsung Galaxy S7 // Android 8
iPhone Xs Max// iOS 15.3
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
