### ISSUE TITLE
Display Cognitive Tasks on Applet Library 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#165]
As an admin, I want to add an activity containing cognitive tasks to the library so that other admins can copy my applet/ activity with cognitive tasks into their own account 

Requirements 
- Allow applets with cognitive tasks to be published to the applet library 
- Do not show item-level options for a cognitive task. Only show the activity level name
- Allow user from the library to copy the applet or activity into their own library to create a new or existing applet

**Comment by natalia-muzyka** [comment]
Issues:
[Flanker] Feedback is shown in the Test blocks in the activity copied from the library #2599

**Comment by natalia-muzyka** [comment]
The implementation met the requirements.
Verified on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 101
macOS Catalina 10.15 // Chrome 101
ML v0.20.4 staging
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
Google Pixel 5a // Android 11
iPad Pro (10,5-inch) MQDX2 // iOS 15.3
