### ISSUE TITLE
Tooltip missing for add activity

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#167]
Add the tooltip for the + button -> "Add Activity" 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/033eed9e-cdd4-4e46-8afa-db2d076fe8ed)

**Comment by natalia-muzyka** [comment]
@WorldImpex this issue is duplicated. it is already resolved. Original:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/710
