### ISSUE TITLE
[Reorder feature] Activities order in the applet library doesn't match the applet builder

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-applet-library#169]
User is logged in to the admin panel
https://admin-staging.mindlogger.org/
bruce_ml@protonmail.com	12345678

**Steps to reproduce**
1. Share with the library the applet with previously changed activities order
2. Compare the order of activities in the library and applet builder
3. Copy the shared applet to any other account (by creating a new applet)
4. Compare the order of activities in the library and applet builder
5. Observe the result

**Actual result**
Activities order in the applet library doesn't match the applet builder. Activities are displayed in alphabet order.

**Expected result**
Activities order in the applet library matches the applet builder

**Notes: Not reproducible on item level**

**Video:** https://www.screencast.com/t/pDCgwfnf9fZ
**Screenshot:**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ba33b047-e5bc-4bd0-8d1b-65b32e30e8bd)

**Environment:**
https://admin-staging.mindlogger.org/
https://library-staging.mindlogger.org/
Win 10 // Chrome 98.0.4758.102 
owner: bruce_ml@protonmail.com	12345678
applet: reordering
copied to: admin.panel@test.com	123456
Applet password	Qwe123!!!

**Comment by WorldImpex** [comment]
fixed
