### ISSUE TITLE
Allow any account to publish an applet to the library 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#172]
Currently, only specific accounts have the ability to publish applets. All accounts should be able to do this going forward

**Comment by natalia-muzyka** [comment]
All PROD accounts have the ability to share applets to the Library now:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e9cc8567-d4e0-44d4-a633-89e39a76e17a)
