### ISSUE TITLE
[PROD] The Flanker_360 activity can be expanded to the item level

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-applet-library#191]
Expected: Cognitive activities shouldn't have an item level.
Notes: Not reproduced with the other Flanker activity in the prod library: https://library.mindlogger.org/#/applets/629677afb90b7f104d02e764?lang=en_US

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ddce5410-d137-44d1-b6ce-e80ed0c8fbf6)

Environment:
Win 10 / Chrome 102
https://library.mindlogger.org/#/applets/629aa196b90b7f104d02ea85?lang=en_US

**Comment by natalia-muzyka** [comment]
@mtg137 there is an issue with displaying and adding the Flanker activity if it has an old version (applet uploaded and edited 3 months ago)

https://www.screencast.com/t/wGFCEUgO2UW

cc: @WorldImpex

**Comment by mtg137** [comment]
![image.png](https://images.zenhubusercontent.com/5fbce3e9259bafeab239c8c3/10fda5a3-b861-48e2-8809-c9a1a30ed16d)

**Comment by natalia-muzyka** [comment]
@mtg137 yes, that's correct, thanks
