### ISSUE TITLE
[PROD] The cumulative applet copied from library contains the cumulative without any selected "Items within cumulative score"

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-applet-library#192]
After completing the activity in the mobile and admin panel PDF report there is an incorrect representation of the score scale.
The applet was only copied from the library (without any additional changes before saving it).

Video: https://www.screencast.com/t/FjQdQhKnvvL

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/53ad4f47-e343-4b3c-ab82-cadaf5e6511e)

Environment:
https://admin.mindlogger.org/
https://library.mindlogger.org/
copied applet link:
https://library.mindlogger.org/#/applets/623cd71f5197b9338bdaf0e4?lang=en_US
anita_ml@protonmail.com	qwe123!!!
PMHSA - RUMC (5-10) / PMHSA
Applet password	Qwe123!!!

**Comment by mtg137** [comment]
I've discussed with @WorldImpex, if there isn't any calculation then the bar is correct.
