### ISSUE TITLE
Flows and activities are copied from the library if all the flow activities were not selected

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-applet-library#197]
**Preconditions**
There is the applet with the activity flow in the library. Some activities are not included in the flow.

**Steps to reproduce**

1. Open a site https://library.mindlogger.org/
2. Proceed to the applet with the flow
3. Copy activities that are not included in the flow or copy not all the activities that are included in the flow
4. Checkout to the new applet
5. Check the Flow tab in the builder

**Actual result**
Empty flow is copied from the library if all the flow activities were not selected to copy

**Expected result**
Flow is not copied from the library if all the flow activities were not selected to copy

**Video**: https://www.screencast.com/t/CubkQqbgkX
https://screencast-o-matic.com/watch/c3QqQxVOy0G
**Environment**
https://library-staging.mindlogger.org/
https://library.mindlogger.org/
Win 10 // Chrome 103

**Comment by e-kass** [comment]
Cannot add a label. Low/Med priority

**Comment by natalia-muzyka** [comment]
Verified as fixed.

Environment:
https://admin-staging.mindlogger.org/
https://library-staging.mindlogger.org/
Win 10 // Chrome 106
macOS 10.15 // Chrome 106 // Safari 13.1.2
