### ISSUE TITLE
[PROD] 403 Error when Copying Applet from Library 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#198]
For some reason [this applet ](https://library.mindlogger.org/#/applets/62e7a2ceacd35a4c635b2165?lang=en_US) causes a 403 error when trying to copy the whole applet and save it to an account

**Comment by natalia-muzyka** [comment]
The issue is fixed. Reminder: the applet can't be saved because of the conditional logic issue, which is not resolved yet.

Video: https://www.screencast.com/t/ITd8RrYSw
