### ISSUE TITLE
Applet Library Search

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#2]
As a non-logged in user, I want to see the shared applets so that I can copy other's content to use in my own account 

Requirements
* Build URLs using library.mindlogger.org 
* Show a keyword search bar at the top of the libray's main page
* Show Basket Icon in top right corner of page 
* Information "I" should send the user to the applet detail page 
* Applets should be shown in alphabetical order by default. 
* Allow the user to expand to see activities 
* Allow the user to expand again to items in a minimized state. 
   * Allow the user to expand each item independently using a +/- button
      * Show checkboxes next to expanded activities and items. 
      * Allow the user to select or deselect activities/ items in the search result being actioned 
   * Keyword search should be all the way to the level of items and include any text throughout the applet 
      * Show keyword found in the search in bold 
   * Show applets then activities and then activities in that order when a keyword search is made 
* If no selection is made then show add to basket icon as greyed out and not actionable 
* Allow the user to sign in and sign out of his or her account 
* Add a link to the applet library from the admin panel 
![Screen Shot 2021-03-09 at 6.42.50 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/52235259-d31e-4d22-957f-8238b09126ce)

![Blank diagram (1).png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/03c63c52-6f71-4e78-8c9e-7dc01015908b)

Applet level Show: 
* Applet name 
* Applet description
* Applet keywords 
* Applet image 

Activity Level Show: 
* Applet name 
* Applet description
* Applet keywords 
* Applet image 
* All activities 

Item Level should not be shown 

Add to basket icon
* Allow a non-logged in user to add applets, activities, and items to the basket 
* The checkbox to the left of the keyword found should be checked

**Comment by jj105** [comment]
backend complete.

**Comment by sergeysemenuta** [comment]
Works as expected according the requirements.
Checked on:
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by natalia-muzyka** [comment]
Requirements: Applets should be shown in alphabetical order by default.
Actual result: The applets ordering depends on capitalization, is it expected?
@WorldImpex @jj105 @binaryExDev

**Comment by WorldImpex** [comment]
@natalia-muzyka No I would say that is a bug

**Comment by natalia-muzyka** [comment]
@WorldImpex @jj105 @binaryExDev 
Should the applet be automatically expanded after searching for some activity/option that is hidden?
Currently, it doesn't, and if the value is placed on a deeper level it stays hidden.
https://www.screencast.com/t/rs82tX4RB1q

New issue was created:
[#53 The applets are automatically deleted from the cart after logging in](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-website/53)

**Comment by WorldImpex** [comment]
Yes that is correct @natalia-muzyka

**Comment by natalia-muzyka** [comment]
Fixed:
#51 The matching results aren't displayed after searching the applet's with the valid keyword if a user isn't on the first page
#52 The applets ordering depends on capitalization
#53 The applets are automatically deleted from the cart after logging in

Waiting for the fix:
[#49 The blank page is displayed after clicking the "See applet detail" button](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/49)
[#1025 The selecting applets/activities is broken on the main page](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1025)
[The applet detail page url isn't specified according to the applet id and the sharing link from the admin panel](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1014)

**Comment by natalia-muzyka** [comment]
Update 01/07 
Waiting for fixes:
[Search Results do not show Keywords always #69](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/69)

**Comment by natalia-muzyka** [comment]
The **Search Results do not show Keywords always #69** is moved to the next release scope.
The current implementation is acceptable and met the requirements.

Tested on:
Windows 10 x64 // Chrome 91.0.4472.124	
macOS  10.15.6 Catalina // Safari // Chrome 91.0.4472.124	
macOS 11.0 BigSur // Safari
