### ISSUE TITLE
Applet Detail Missing Response Options

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#24]
Expected: Response options are shown and item question is shown. Response options should have the response option type icon next to them 
Actual: Only the item name is shown

Note: Item/ response options should also show on the search results page. The user should not have the option to select each item but should be able to expand and collapse the sections 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/ea5cb3d6-67dc-4615-a748-3cdcb09e3384)

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/50881c01-dd20-4eca-bcf3-a1106e68bd34)

**Comment by binaryExDev** [comment]
@WorldImpex I've a couple of questions.
I displayed the response options for radio/checkbox items but what are response options for date picker?
Should I show item question instead of item name?

**Comment by WorldImpex** [comment]
@binaryExDev On items that do not have a specific option we can mimic the text and image from the applet builder 

![image](https://user-images.githubusercontent.com/22243307/116876603-bdcda500-abea-11eb-80b0-b83e4d33896e.png)

**Comment by WorldImpex** [comment]
1. Random "radio" item is shown in list 
2. Replace "item name" (item 1) with "large text" (Did you sleep well?) - This change should be in search results, detail page, basket, etc. 
![Screen Shot 2021-05-05 at 5.26.38 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/ced58a38-ae7c-4c33-8915-2ac64c8f0284)

![Screen Shot 2021-05-05 at 5.26.01 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/f5340856-9ee4-4fe8-b1a9-45a02537c1ca)

3. Images do not match what was built in the applet builder

![Screen Shot 2021-05-05 at 5.29.52 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c620beaf-37db-4b6f-b671-4838f273e1e1)

**Comment by WorldImpex** [comment]
works as expected 

![Screen Shot 2021-05-10 at 4.49.40 AM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/0f9f2296-8d85-4aec-8fd0-471ab94cb8ee)
