### ISSUE TITLE
Implement Pagination on Search Page

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#29]
* Show the user 25 applets with the ability to page or expand the results by increments of 25

**Comment by binaryExDev** [comment]
@WorldImpex Would you please take a look at this link and let me know if this is what we need for pagination?

https://vuetifyjs.com/en/components/paginations/

**Comment by WorldImpex** [comment]
@binaryExDev Yes that looks good. Please ensure it mirrors other pagination we have in ML - 

![image](https://user-images.githubusercontent.com/22243307/118485086-f343b980-b6e5-11eb-8f24-174ff3c716d8.png)

**Comment by sergeysemenuta** [comment]
The implemented pagination in the library doesn't match the style as on the admin panel. It should have the same style as on the admin panel.
![2021-05-21_11-18-49.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/56914a2f-747f-47c4-9d8d-c0f91185f875)

https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by binaryExDev** [comment]
@WorldImpex The expected pagination that you're saying is the pagination provided by vuetify table but for the applets, I need to use separate pagination component and it couldn't be the same with table pagination.

**Comment by natalia-muzyka** [comment]
@WorldImpex @binarybottle could you clarify, please:
As I understood, there is  a typo in the requirements:
> by increments of 25
Currently, there are 5 applets per page
https://www.screencast.com/t/WokR1UWB5gD

Environment:
https://library-staging.mindlogger.org/ 
Win 10 // Chrome 91.0.4472.77

**Comment by WorldImpex** [comment]
@natalia-muzyka / @jj105 

The user should have 25 applets on one page with the option to show more than 25 applets in increments of 25 like we do on admin. The # per page is a bit flexible based on the library and performance concerns

**Comment by natalia-muzyka** [comment]
Current implementation still has some differences from an admin panel but works well:
The user has 5 applets per one page by default and can increase the quantity of displaying to 10, 25, 50, and 100.
The pages quantity changes according to the selected step "Rows per page".
https://www.screencast.com/t/Djpqcp2rg
@WorldImpex Is this implementation acceptable?

**Comment by WorldImpex** [comment]
Yes just as long as there aren't any latency or usability issues then this is acceptable @natalia-muzyka

**Comment by natalia-muzyka** [comment]
Verified and closed
Environment:
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.77
