### ISSUE TITLE
Remove Legacy Applets in Library

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#30]
Applets that were deleted before the deleting function worked are still present. 

We need to delete the below applets that still show in the library 
Date picker applet library
Delete from the library x2
LOOKUP1
LOOKUP1asd
Mental Health
STACKED
TOKENLOGGER (Prizes)
Token Applet
Token Logger Applet
Tucker
Wil's Applet
Wil's Applet (1)

**Comment by sergeysemenuta** [comment]
Applets are removed from the Library
https://library-staging.mindlogger.org/
