### ISSUE TITLE
Applet Detail Page

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#4]
As a user of MindLogger, I want to see an applet detail page so that I can learn about what contents are in an applet. 

Requirements 
* Based on the link created with [this effort](https://app.zenhub.com/workspaces/mindlogger-applet-library-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/1), the link should open the detail page for that applet 
* Header: 
   * Should show CMI logo and MindLogger Library on right side
   * Basket and Login should be on the right side
Applet Detail: 
* Show 
   * Applet Image Icon 
   * Applet Name
   * Applet Description 
   * Applet Version Number
   * Add to basket Icon (Tooltip: Add items to basket) 
* Allow the user to expand Activities > Items > Response options 
* Show Activity name > Item Question > Response option items with icons and response option type icon
   * Response option type icons should be in grey 
* If the user selects Backet Icon, then expand toolbar with select all, add to basket and a cancel button 
   * Show checkboxes at the activity and items level 
   * Allow the user to select one or more or all activities for the applet. 
   * Show text of selection made in real-time updates (1 item selected, etc) 
   * When user selects add to basket, then update the basket with the number of items added 
   * By hitting cancel, any selection made is unchecked and the screen goes back to the original 
![Blank diagram.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/fdc0bba7-7800-4902-9057-f41666e2cd9c)

**Comment by WorldImpex** [comment]
backend complete

**Comment by natalia-muzyka** [comment]
[#1014 There is a wrong path for a copied link to share an applet with others ](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1014)

[#1000 The 'View All Contributions' link is missing on the applet detail page](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1000)

[#49 The applet detail page url isn't specified according to the applet id and the sharing link from the admin panel
](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/49)

UI issue: Response option type icons aren't greyed
![response options.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/b6a21d7f-ce85-4f5a-973f-97c3bd641cec)

**Comment by natalia-muzyka** [comment]
Works as expected. All the issues are fixed.

Checked on:
Win 10 // Chrome 91.0.4472.124
