### ISSUE TITLE
Hide Category selection 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#40]
Please hide the category section when uploading a new applet or editing an existing one in the library and make it not required for a user to publish an applet. We will be deploying without this feature for now

**Comment by Sshetty2** [comment]
@WorldImpex Do we also want to hide the sub-category section?

**Comment by WorldImpex** [comment]
@Sshetty2 Yes please

**Comment by sergeysemenuta** [comment]
The Category and sub-cutecory are hidden
![2021-05-25_9-53-17.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/7eb00a2d-634e-4804-a521-4de935f74106)
Checked on:
https://admin-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)
