### ISSUE TITLE
Item is only for Mobile Use Indicator 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#42]
Show next to item type in red (For use in the mobile version of MindLogger only)
* All items should have this except radio button, checkbox, slider, and textbox 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/e365070a-3f35-4b1b-bf50-745a507b8df5)

**Comment by natalia-muzyka** [comment]
Verified
https://www.screencast.com/t/9AbTwmVKWa

Checked on:
Win 10 // Chrome 92.0.4515.107 
macOS 10.15.6 // Safari 13.1.2 (15609.3.5.1.3) // Chrome 92.0.4515.107
