### ISSUE TITLE
View Basket 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#6]
As a user, I want to view my basket so I can confirm the content I am going to copy into my applet builder 

Requirements 
* If user selects the checkout icon in the search or header then this page should be shown 
* Show a search bar at the top of the page with a "Add to Builder" button next to it 
* Show a blank state with text "You have not added anything to your basket yet. Start searching above." 
* Applets are shown on the item list of the basket and the selections made are shown on the activity and item levels 
* Show
   * Applet Name
   * Applet Description 
   * Keywords
   * Applet Image Icon 
* Allow the user to select or unselect items within an activity in a cart 
* Allow user to expand and contrast using the +/- buttons to show other content in the applet. 
   * The user should be able to select/ unselect items in the expansion of sections of the applet 
* Allow the user to delete an applet using the trashcan
   * Show a confirmation message if the user tries to delete, "Are you sure you want to delete " **Applet Name** from your basket? "
   * If the user unselects the last selection in an applet then show a confirmation message to delete "Are you sure you want to delete " **Applet Name** " from your basket?" 

![Blank diagram.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/5ae24004-8bb7-458e-8410-9a7eba80f3a7)

**Comment by jj105** [comment]
backend complete.

**Comment by sergeysemenuta** [comment]
Works as expected according the requirements
Video: https://www.screencast.com/t/nkfvfLnPve
Checked on: https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

This ticket can be closed.
