### ISSUE TITLE
Infinity loader on Applet Library. The part of applets can't be loaded and added to the cart

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-applet-library#64]
**Steps to reproduce**
1. Open a site https://library-staging.mindlogger.org/
2. Select "rows per page: 100" (for displaying all the applets on one page)
3. Scroll down the page
4. Pay attention to the screen

**Actual result**
Infinity loader on Applet Library. The part of applets can't be loaded and added to the cart. If the user uses a default view (5 rows per page) the issue is located on the 4th page.

**Expected result**
Applet Library is displayed fully. All the applets are available.

Notes:
Reproducible for the authorized and non-authorized user. 

**Attachment**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/aa8a0498-808a-4822-9c38-1e433b839851)
https://images.zenhubusercontent.com/103405139/0f1a9deb-34a2-4b9e-9aa6-b99f7920b290/bandicam_2021_06_10_10_44_58_478.mp4

**Environment**
https://library-staging.mindlogger.org/
Win 10 // Google Chrome 91.0.4472.77

**Comment by binaryExDev** [comment]
Fixed. Waiting for deploying this PR - https://github.com/ChildMindInstitute/mindlogger-backend/pull/1070

**Comment by natalia-muzyka** [comment]
The issue with loading is fixed but some applets which are out of the previous scope still can't be added to the cart. I created a separate issue for them: [#67 Some applets can't be added to the cart(server error)]
(https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/67)

Environment
https://library-staging.mindlogger.org/
Win 10 // Google Chrome 91

**Comment by natalia-muzyka** [comment]
@binaryExDev 
**The issue is reproducible again and locates on the 5th page in the default view.**
The user is able to add an applet to the cart but the server error appears after an attempt to proceed to applet builder.

Attachments:
https://www.screencast.com/t/Ce3T5WardHs
https://www.screencast.com/t/nWcZLzLAabVe

Environment
https://library-staging.mindlogger.org/
Win 10 // Google Chrome 91
account: geria.test@gmail.com // 123456

**Comment by WorldImpex** [comment]
@binaryExDev Let me know if this is specific to demo applet. There are a lot of features that might not be covered by the libray

**Comment by natalia-muzyka** [comment]
Not reproduced
https://www.screencast.com/t/t59hgrbRj0j
https://www.screencast.com/t/9wz9uOEe

Environment
https://library-staging.mindlogger.org/
Win 10 // Google Chrome 91
account: geria.test@gmail.com // 123456
ML Demo applet

**Comment by natalia-muzyka** [comment]
Reproduces again.
**Infinity loader on Applet Library. Currently, all the applets can't be added to the cart.**

video: https://www.screencast.com/t/lIss6x7EdtSB
screenshot with server error: https://www.screencast.com/t/0YNUmjjgrUN

Environment
Win 10 // Chrome 91
macOS Big Sur 11.0 // Safari // Chrome 91

**Comment by Matchdev120** [comment]
@natalia-muzyka @binaryExDev 
Just experienced one issue on applet library - AppletTrees and Checkboxes are invisible now.

**Comment by WorldImpex** [comment]
Fixed - Google Chrome Version 91.0.4472.114

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/YTNG6v3MC5Wb

Environment
https://library-staging.mindlogger.org/
Win 10 // Google Chrome 91.0.4472.114
