### ISSUE TITLE
The ability to expand/collapse the activity item is missed

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-applet-library#72]
**Preconditions**
The site https://library-staging.mindlogger.org/ is opened
The user is logged in

**Steps to reproduce**
1. Add an applet with at least to the cart
2. Proceed to the cart page
3. Expand the activity to the lowest item level
4. Observe the result

**Actual result**
The ability to expand/collapse the activity item is missed(to see/hide the item options).

**Expected result**
The ability to expand/collapse the activity item is present in the Applet library. As per requirements:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/2
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/85

**Attachment**
![46debeb5-6951-46e0-9ec7-a815d077fd63.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4b89a4a3-d4dc-46b3-8ed7-6a9ad82bcb22)

**Environment**
https://library-staging.mindlogger.org/
Win 10 // Chrome 91

**Comment by natalia-muzyka** [comment]
@binaryExDev 
**1) On the cart page the issue is still reproduced**
https://www.screencast.com/t/fMIVz15UgRWo

**2) For some applets the expanding doesn't work**
https://www.screencast.com/t/KHgeOEyVf

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91

**Comment by natalia-muzyka** [comment]
Testing is blocked by https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/64

**Comment by WorldImpex** [comment]
Fixed - Google Chrome Version 91.0.4472.114

**Comment by natalia-muzyka** [comment]
Not reproduced

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.114
