### ISSUE TITLE
Reviewer Dashboard Assessment

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#8]
As an editor, I want to create an assessment that is shown to the reviewer while looking at a user's data so that the reviewer can answer questions about the data he or she is looking at 

Goal: Allow an editor to create an activity within an applet that is only shown on the reviewer dashboard.

Requirements: 
Builder
* Have the editor select a button to create an activity to be shown on the user's data visualization as a new tab called "Review" 
![Expert Review - Applet Builder.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/850d3e41-0b68-4b8a-8035-a8d4639821d8)
* Allow the editor to only use radio button, checkbox, slider with conditional logic to create this type of activity. 
** Tokens, Scores, Set Alet, is not necessary if it is easier to implement without it 
** Images should be able to be uploaded 
** Allow the reviewer to click the review tab and select a specific date to review or select a compliance circle to review 
Assessment 
* When a date has been selected so the user's response details with all questions, response options, and items selected with the assessment created in the right pane  
* Follow webapp UI when displaying questions (stacking new questions at the top, etc) 
* Allow the reviewer to only complete the assessment once but allow that reviewer to edit responses
** If a response was edited, change it in the review and add (edited) next to the question
* if a reviewer or manager has completed the reviewer assessment add the results from their review to a "Reviewed" tab to show the questions, response options and options selected by each reviewer/ manager 
* Notes tab is not scope for this ticket 
![Reviewer Dashboard .png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4cb6dd50-e2d7-4d74-af0f-97eb3d26344a)

**Comment by HarutQA** [comment]
Works correctly.
