### ISSUE TITLE
The "Login" modal window isn't closed and transferring applet process isn't continued after logging in via cart

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-applet-library#89]
**Steps to reproduce**
1. Open a site https://library-staging.mindlogger.org/
2. Add any applet to the cart
3. Click "Add to applet builder"
4. Enter valid credentials
5. Pay attention to the screen

**Actual result**
The "Login" modal window isn't closed and transferring applet process isn't continued after logging in via cart

**Expected result**
The "Login" modal window is closed and transferring applet process isn't continued after logging in via cart

**Attachment**
https://images.zenhubusercontent.com/103405139/5415b205-4031-4256-a290-d342bd350c67/login_via_cart.mp4

**Environment**
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.114

**Comment by Sshetty2** [comment]
@binaryExDev 
https://github.com/ChildMindInstitute/mindlogger-applet-library/commit/5cdd8ed8b691963e025704d6f763eac3b1dbde30#r52824752

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/bKkxk1X1

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.114

**Comment by natalia-muzyka** [comment]
@Sshetty2 @binaryExDev 
**The issue is reproducible with these steps:**
1. Share any applet with the library and Copy the applet link on the admin panel
2. Open the applet detail page with a copied link
3. Add applet / activities to the cart from the detail page
4. Proceed to the cart and pay attention to the screen
5. Log in with valid credentials
6. Pay attention to the screen

**Additional info: The checkboxes on the applet/activity/item level aren't displayed on the cart page while the user isn't logged in. The authorization form can be disappeared only by refreshing the page. **

Video: https://www.screencast.com/t/PPVWVvmDH

Environment:
https://admin-staging.mindlogger.org/
https://library-staging.mindlogger.org/
Win 10 // Chrome 93.0.4577.82 
macOS 11.0 // Safari 14.0.1
owner: geria.test@gmail.com	// 123456
johndoeregress@protonmail.com	// 12345678
applet: transfer + dataviz check
Applet password:	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed.
Video: https://www.screencast.com/t/axxxyZZL

Environment:
https://admin-staging.mindlogger.org/
https://library-staging.mindlogger.org/
Win 10 // Chrome 94.0.4606.61 
owner: geria.test@gmail.com // 123456
geria.test@yahoo.com // 3FuuFz60
applet: transfer + dataviz check
Applet password: Qwe123!!!
