### ISSUE TITLE
The changes made by the current owner are replaced for the item instead of adding a new line to the table with a new applet name

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-applet-library#92]
**Preconditions**
The site is opened https://admin-staging.mindlogger.org/
The user is logged in geria1.test@gmail.com	// 7clCm7D5
There is a copied from a library and shared applet "Original applet (1) transferred 4"

**Steps to reproduce**
1. Open a site https://library-staging.mindlogger.org/
2. Proceed to the "Original applet (1) transferred 4" detail page 
3. Click the "View all contributions" -> "View"
4. Open an applet builder for the "Original applet (1) transferred 4" admin panel
5. Made any changes in existing activity
6. Proceed to the "Original applet (1) transferred 4" detail page
7. Refresh the page
8. Click the "View all contributions" -> "View"
9. Pay attention to the changes in the table

**Actual result**
The changes made by the current owner are replaced in the same line for the changed item. 

**Expected result**
The new line with appropriate info is added to the table after editing the applet by the current owner.

**Attachment**
https://www.screencast.com/t/r8C5Gwqm
https://www.screencast.com/t/eVX0VYdY

**Environment**
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.114
Applet:
Original applet (1) transferred 4 
Applet password: Qwe123!!!

**Comment by WorldImpex** [comment]
@natalia-muzyka if we retain the original version (if the applet was created via builder or copied from library) and the latest change made to the applet then we should be okay. We do not need to see the same owner's changes to the applet historically

**Comment by natalia-muzyka** [comment]
@WorldImpex do you mean that we should see only the latest changes if they were made by the same owner?

I'm sorry if the applets naming is confusing. 
Anyway, I think there is still an issue. The point is that the applet #3 "changes" (original owner: John) were replaced by applet #4 changes (current, copied from applet #3, the current owner is Geria1):
https://content.screencast.com/users/TestAccount9219/folders/Snagit/media/6c75cf65-deb5-4ec2-ba46-4aca2b132f33/06.30.2021-14.23.png

**Comment by WorldImpex** [comment]
@natalia-muzyka Perfect! Yes you are correct that is an issue. We should see changes from John and the latest update from Geria1

**Comment by natalia-muzyka** [comment]
Verified as fixed
https://www.screencast.com/t/zpSzdvrxRV

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.114
