### ISSUE TITLE
UI/UX Contributions table issues

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-applet-library#94]
**1. The horizontal scroll is displayed for the big tables**
https://www.screencast.com/t/ZcQgdQdF0M

**2. The table headers aren't vertically aligned**
https://www.screencast.com/t/vjn01orMyLU

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.114
Applets:
A a Nice applet 111
Original applet (1) transferred 4

**Comment by WorldImpex** [comment]
Horizontal scrolling should be fine

**Comment by natalia-muzyka** [comment]
Fixed: The table headers are vertically aligned

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.114
